version: '3'
services:
  csvweb:
    image: infracloudio/csvserver:latest
    ports:
      - 9393:9300
    volumes:
      - /csvserver/inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER:orange

